export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_RECEIVE = 'FETCH_CATEGORIES_RECEIVE';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_RECEIVE = 'FETCH_POSTS_RECEIVE';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const POST_VOTE_SCORE = 'POST_VOTE_SCORE';
